services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "80:80"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  dbdata:
